apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-example
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command: ["git", "clone", "https://github.com/yugyogeshpawar/instant-help.git", "/shared"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  restartPolicy: Always

