apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-example
spec:
  volumes:
    - name: shared-data
      emptyDir: {} # Shared storage for communication
  initContainers:
    - name: clone-repo
      image: alpine/git # Image with Git installed
      command: ["/bin/sh", "-c"]
      args:
        - |
          git clone https://github.com/Anshuman2121/netflix-clone.git /shared
          
      volumeMounts:
        - name: shared-data
          mountPath: /shared
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html # Serve the cloned files
  restartPolicy: Always
